### ISSUE TITLE
Enhanced Tracking Protection automatically resets to Standard after every browser restart.

### ISSUE THREAD

**Issue by onthejobtraining** [zen-browser/desktop#1220]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Method to reproduce the error:
1. Go to Settings>Privacy and Security.
2. Set Enhanced Tracking Protection to Strict or Custom
3. Restart Zen Browser
4. Go to Settings>Privacy and Security

You'll see that the ETP level has been reset to Standard.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by DaniilSkLi** [comment]
Have you solved the problem? If so, would you mind sharing how? I'm having the same problem. I'm using version 1.0.0-a.37 from flathub.

**Comment by mauro-balades** [comment]
maybe in the about:config you can change it, the id is `browser.contentblocking.category`

**Comment by DaniilSkLi** [comment]
Didn't help( After restart it resets to standard

https://github.com/user-attachments/assets/c5fd2727-b4f9-41c0-8008-7fcef1df4ae9

**Comment by onthejobtraining** [comment]
Issue hasn't been fixed, but there was already a bug report filed that I missed when I created this ticket, so I closed it later on.

Here's the original Bug Report: https://github.com/zen-browser/desktop/issues/202
