### ISSUE TITLE
Tracking Shield Container is not aligned with other Icons and some other design issues

### ISSUE THREAD

**Issue by shettytejas** [zen-browser/desktop#1628]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?
![Screenshot 2024-09-23 192028](https://github.com/user-attachments/assets/a628a149-50c7-4569-8d0b-53f8a09c3172)

1. The tracking shield container is not aligned with the other icons and seems off.
2. The border radius between toolbar icons and url bar doesn't seem consistent.
3. Padding on block is inconsistent with inline padding.
4. ... (Will be updating some more design issues)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

 1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Should be fixed in the newer updates, will be closing this. Please reopen if this still persists.
